/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_SENAP;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.org.inegi.ExportaXlsm.SENAP.Exporta_errores_insert;
import mx.org.inegi.QuerysGeneralOracle.SENAP.QueryOracle;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Errores_insertTR extends javax.swing.JFrame {

    /**
     * Creates new form Errores_insertTR
     */
    public Errores_insertTR() {
        initComponents();
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        ExportaEi.setVisible(false);
        jProgressBar1.setVisible(false);
        jTextArea1.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExportaEi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ExportaEi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exporta.png"))); // NOI18N
        ExportaEi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportaEiActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refresh.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TABLA", "REG_ID", "CAMPO", "EXCEPCION"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExportaEi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExportaEi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExportaEiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportaEiActionPerformed
        // TODO add your handling code here:
        IntegraTR Pintegra = new IntegraTR();
        Exporta_errores_insert ErroresInsert = new Exporta_errores_insert();
        try {
            ErroresInsert.exportarExcel(jTable1, Pintegra.Entidad, Pintegra.Periodo);
        } catch (IOException ex) {
            Logger.getLogger(Errores_insertTMP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ExportaEiActionPerformed

     public void limpiarTabla() {
        DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
        while (TablaError.getRowCount() > 0) {
            TablaError.removeRow(0);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Thread(() -> {
            limpiarTabla();
            MuestraError();
        }).start();

        }

        public void MuestraError() {
            try {
                jTextArea1.setVisible(false);
                jProgressBar1.setVisible(false);
                ExportaEi.setVisible(false);
                jButton1.setEnabled(false);
                String Texto = "";
                String regTMPOracle = "", regTROracle = "";
                ArrayList<String[]> ArrayErroresIns;
                QueryOracle Q = new QueryOracle();
                IntegraTR Pintegra = new IntegraTR();
                 String[] ArrayTablasTMPOracle = new String[24];
                ArrayTablasTMPOracle[0] = "RES_TMP_SENAP_ACTOSINVESTIGACION";
                ArrayTablasTMPOracle[1] = "RES_TMP_SENAP_ASEGURAMIENTOS";
                ArrayTablasTMPOracle[2] = "RES_TMP_SENAP_ATENCIONES";
                ArrayTablasTMPOracle[3] = "RES_TMP_SENAP_CARPETAINVESTIGACION";
                ArrayTablasTMPOracle[4] = "RES_TMP_SENAP_DELITOS";
                ArrayTablasTMPOracle[5] = "RES_TMP_SENAP_DETERMINACION";
                ArrayTablasTMPOracle[6] = "RES_TMP_SENAP_DIRECCIONUBICACION";
                ArrayTablasTMPOracle[7] = "RES_TMP_SENAP_ETAPAINTERMEDIA";
                ArrayTablasTMPOracle[8] = "RES_TMP_SENAP_ETAPAINVESTIGACION";
                ArrayTablasTMPOracle[9] = "RES_TMP_SENAP_IMPUTADO";
                ArrayTablasTMPOracle[10] = "RES_TMP_SENAP_IMPUTADODELITO";
                ArrayTablasTMPOracle[11] = "RES_TMP_SENAP_INVESTIGACIONCOMPLEMENTARIA";
                ArrayTablasTMPOracle[12] = "RES_TMP_SENAP_MANDAMIENTOSJUDICIALES";
                ArrayTablasTMPOracle[13] = "RES_TMP_SENAP_MASC";
                ArrayTablasTMPOracle[14] = "RES_TMP_SENAP_MEDIDASCAUTELARES";
                ArrayTablasTMPOracle[15] = "RES_TMP_SENAP_MEDIDAS_PROTECCION";
                ArrayTablasTMPOracle[16] = "RES_TMP_SENAP_NOTICIACRIMINAL";
                ArrayTablasTMPOracle[17] = "RES_TMP_SENAP_PROCESO";
                ArrayTablasTMPOracle[18] = "RES_TMP_SENAP_SENTENCIA";
                ArrayTablasTMPOracle[19] = "RES_TMP_SENAP_SOBRESEIMIENTO";
                ArrayTablasTMPOracle[20] = "RES_TMP_SENAP_SUSPENSIONCONDICIONAL";
                ArrayTablasTMPOracle[21] = "RES_TMP_SENAP_VICTIMAIMPUTADO";
                ArrayTablasTMPOracle[22] = "RES_TMP_SENAP_VICTIMAS";
                ArrayTablasTMPOracle[23] = "RES_TMP_SENAP_VICTIMASDELITO";
                
                String[] ArrayTablasTROracle = new String[24];
                ArrayTablasTROracle[0] = "RES_TR_SENAP_ACTOSINVESTIGACION";
                ArrayTablasTROracle[1] = "RES_TR_SENAP_ASEGURAMIENTOS";
                ArrayTablasTROracle[2] = "RES_TR_SENAP_ATENCIONES";
                ArrayTablasTROracle[3] = "RES_TR_SENAP_CARPETAINVESTIGACION";
                ArrayTablasTROracle[4] = "RES_TR_SENAP_DELITOS";
                ArrayTablasTROracle[5] = "RES_TR_SENAP_DETERMINACION";
                ArrayTablasTROracle[6] = "RES_TR_SENAP_DIRECCIONUBICACION";
                ArrayTablasTROracle[7] = "RES_TR_SENAP_ETAPAINTERMEDIA";
                ArrayTablasTROracle[8] = "RES_TR_SENAP_ETAPAINVESTIGACION";
                ArrayTablasTROracle[9] = "RES_TR_SENAP_IMPUTADO";
                ArrayTablasTROracle[10] = "RES_TR_SENAP_IMPUTADODELITO";
                ArrayTablasTROracle[11] = "RES_TR_SENAP_INVESTIGACIONCOMPLEMENTARIA";
                ArrayTablasTROracle[12] = "RES_TR_SENAP_MANDAMIENTOSJUDICIALES";
                ArrayTablasTROracle[13] = "RES_TR_SENAP_MASC";
                ArrayTablasTROracle[14] = "RES_TR_SENAP_MEDIDASCAUTELARES";
                ArrayTablasTROracle[15] = "RES_TR_SENAP_MEDIDAS_PROTECCION";
                ArrayTablasTROracle[16] = "RES_TR_SENAP_NOTICIACRIMINAL";
                ArrayTablasTROracle[17] = "RES_TR_SENAP_PROCESO";
                ArrayTablasTROracle[18] = "RES_TR_SENAP_SENTENCIA";
                ArrayTablasTROracle[19] = "RES_TR_SENAP_SOBRESEIMIENTO";
                ArrayTablasTROracle[20] = "RES_TR_SENAP_SUSPENSIONCONDICIONAL";
                ArrayTablasTROracle[21] = "RES_TR_SENAP_VICTIMAIMPUTADO";
                ArrayTablasTROracle[22] = "RES_TR_SENAP_VICTIMAS";
                ArrayTablasTROracle[23] = "RES_TR_SENAP_VICTIMASDELITO";
               
                ArrayErroresIns=Q.TotalErrores_insert_SENAP_TR(Pintegra.Entidad, Pintegra.Periodo);
                jProgressBar1.setVisible(true);
                int Contador = 20;
                for (int i = 0; i < 24; i++) {
                    regTMPOracle = Q.Total_Reg_TMP_Oracle(ArrayTablasTMPOracle[i], Pintegra.Entidad, Pintegra.Periodo);
                    regTROracle = Q.Total_Reg_TR_Oracle(ArrayTablasTROracle[i], Pintegra.Entidad, Pintegra.Periodo);
                    Texto = Texto + "" + ArrayTablasTROracle[i] + ": \n"
                    + "Reg_TMP:" + regTMPOracle + "  Reg_TR:" + regTROracle + "\n \n";
                    jProgressBar1.setValue(Contador);
                    Contador = Contador + 4;
                }   jTextArea1.setText(Texto);
                jTextArea1.setVisible(true);
                if (ArrayErroresIns.size() > 0) {
                    String[] errorarray;
                    String part0 = "", part1 = "", part2 = "", part3 = "";
                    DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
                    Object[] fila = new Object[5];
                    for (int j = 0; j < ArrayErroresIns.size(); j++) {
                        String Datos = Arrays.toString(ArrayErroresIns.get(j)).replace("[", "").replace("]", "");
                        errorarray = Datos.split(",");
                        part0 = errorarray[0].trim();
                        part1 = errorarray[1].trim();
                        part2 = errorarray[2].trim();
                        part3 = errorarray[3].trim();
                        fila[0] = part0;
                        fila[1] = part1;
                        fila[2] = part2;
                        fila[3] = part3;
                        TablaError.addRow(fila);
                        Class<?> col_class = jTable1.getColumnClass(0);
                        jTable1.setDefaultEditor(col_class, null);
                    }
                    ExportaEi.setVisible(true);
                    jButton1.setEnabled(true);
                } else {

                    JOptionPane.showMessageDialog(null, "No se encontraron registros con Error de insert", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Errores_insertTMP.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
      
        IntegraTR.ventanaAbierta=false;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Errores_insertTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Errores_insertTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Errores_insertTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Errores_insertTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Errores_insertTR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExportaEi;
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
