/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_SENAP;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.org.inegi.ExportaXlsm.SENAP.Exporta_errores_insert;
import mx.org.inegi.QuerysGeneralOracle.SENAP.QueryOracle;
import mx.org.inegi.QuerysGeneralSQLSERVER.SENAP.QuerySQLServer;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Errores_insertTMP extends javax.swing.JFrame {

    /**
     * Creates new form Errores_insertTMP
     */
    public Errores_insertTMP() {
        initComponents();
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        ExportaEi.setVisible(false);
        jProgressBar1.setVisible(false);
        jTextArea1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ExportaEi = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TABLA", "REG_ID", "CAMPO", "EXCEPCION"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);

        ExportaEi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Exporta.png"))); // NOI18N
        ExportaEi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportaEiActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refresh.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExportaEi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExportaEi)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExportaEiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportaEiActionPerformed
        // TODO add your handling code here:
        IntegraTMP Pintegra = new IntegraTMP();
        Exporta_errores_insert ErroresInsert = new Exporta_errores_insert();
        try {
            ErroresInsert.exportarExcel(jTable1, Pintegra.Entidad, Pintegra.Periodo);
        } catch (IOException ex) {
            Logger.getLogger(Errores_insertTMP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ExportaEiActionPerformed

    public void limpiarTabla() {
        DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
        while (TablaError.getRowCount() > 0) {
            TablaError.removeRow(0);
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Thread(() -> {
            limpiarTabla();
            MuestraError();
        }).start();

    }

    public void MuestraError() {
        try {
            jTextArea1.setVisible(false);
            jProgressBar1.setVisible(false);
            ExportaEi.setVisible(false);
            jButton1.setEnabled(false);
            String Texto = "";
            String regTMPSQL = "", regTMPOracle = "", RegValidacion = "";
            ArrayList<String[]> ArrayErroresIns;
            QueryOracle Q = new QueryOracle();
            QuerySQLServer S = new QuerySQLServer();
            IntegraTMP Pintegra = new IntegraTMP();
            String[] ArrayTablasSQLSERVER = new String[26];
            ArrayTablasSQLSERVER[0] = "SENAP_ACTOSINVESTIGACION";
            ArrayTablasSQLSERVER[1] = "SENAP_ASEGURAMIENTOS";
            ArrayTablasSQLSERVER[2] = "SENAP_ATENCIONES";
            ArrayTablasSQLSERVER[3] = "SENAP_CARPETAINVESTIGACION";
            ArrayTablasSQLSERVER[4] = "SENAP_DELITOS";
            ArrayTablasSQLSERVER[5] = "SENAP_DETERMINACION";
            ArrayTablasSQLSERVER[6] = "SENAP_DIRECCIONUBICACION";
            ArrayTablasSQLSERVER[7] = "SENAP_ETAPAINTERMEDIA";
            ArrayTablasSQLSERVER[8] = "SENAP_ETAPAINVESTIGACION";
            ArrayTablasSQLSERVER[9] = "SENAP_IMPUTADO";
            ArrayTablasSQLSERVER[10] = "SENAP_IMPUTADODELITO";
            ArrayTablasSQLSERVER[11] = "SENAP_INVESTIGACIONCOMPLEMENTARIA";
            ArrayTablasSQLSERVER[12] = "SENAP_MANDAMIENTOSJUDICIALES";
            ArrayTablasSQLSERVER[13] = "SENAP_MASC";
            ArrayTablasSQLSERVER[14] = "SENAP_MEDIDASCAUTELARES";
            ArrayTablasSQLSERVER[15] = "SENAP_MEDIDAS_PROTECCION";
            ArrayTablasSQLSERVER[16] = "SENAP_NOTICIACRIMINAL";
            ArrayTablasSQLSERVER[17] = "SENAP_PROCESO";
            ArrayTablasSQLSERVER[18] = "SENAP_SENTENCIA";
            ArrayTablasSQLSERVER[19] = "SENAP_SOBRESEIMIENTO";
            ArrayTablasSQLSERVER[20] = "SENAP_SUSPENSIONCONDICIONAL";
            ArrayTablasSQLSERVER[21] = "SENAP_VICTIMAIMPUTADO";
            ArrayTablasSQLSERVER[22] = "SENAP_VICTIMAS";
            ArrayTablasSQLSERVER[23] = "SENAP_VICTIMASDELITO";
            String[] ArrayTablasOracle = new String[26];
            ArrayTablasOracle[0] = "RES_TMP_SENAP_ACTOSINVESTIGACION";
            ArrayTablasOracle[1] = "RES_TMP_SENAP_ASEGURAMIENTOS";
            ArrayTablasOracle[2] = "RES_TMP_SENAP_ATENCIONES";
            ArrayTablasOracle[3] = "RES_TMP_SENAP_CARPETAINVESTIGACION";
            ArrayTablasOracle[4] = "RES_TMP_SENAP_DELITOS";
            ArrayTablasOracle[5] = "RES_TMP_SENAP_DETERMINACION";
            ArrayTablasOracle[6] = "RES_TMP_SENAP_DIRECCIONUBICACION";
            ArrayTablasOracle[7] = "RES_TMP_SENAP_ETAPAINTERMEDIA";
            ArrayTablasOracle[8] = "RES_TMP_SENAP_ETAPAINVESTIGACION";
            ArrayTablasOracle[9] = "RES_TMP_SENAP_IMPUTADO";
            ArrayTablasOracle[10] = "RES_TMP_SENAP_IMPUTADODELITO";
            ArrayTablasOracle[11] = "RES_TMP_SENAP_INVESTIGACIONCOMPLEMENTARIA";
            ArrayTablasOracle[12] = "RES_TMP_SENAP_MANDAMIENTOSJUDICIALES";
            ArrayTablasOracle[13] = "RES_TMP_SENAP_MASC";
            ArrayTablasOracle[14] = "RES_TMP_SENAP_MEDIDASCAUTELARES";
            ArrayTablasOracle[15] = "RES_TMP_SENAP_MEDIDAS_PROTECCION";
            ArrayTablasOracle[16] = "RES_TMP_SENAP_NOTICIACRIMINAL";
            ArrayTablasOracle[17] = "RES_TMP_SENAP_PROCESO";
            ArrayTablasOracle[18] = "RES_TMP_SENAP_SENTENCIA";
            ArrayTablasOracle[19] = "RES_TMP_SENAP_SOBRESEIMIENTO";
            ArrayTablasOracle[20] = "RES_TMP_SENAP_SUSPENSIONCONDICIONAL";
            ArrayTablasOracle[21] = "RES_TMP_SENAP_VICTIMAIMPUTADO";
            ArrayTablasOracle[22] = "RES_TMP_SENAP_VICTIMAS";
            ArrayTablasOracle[23] = "RES_TMP_SENAP_VICTIMASDELITO";
            ArrayErroresIns=Q.TotalErrores_insert_SENAP_TMP(Pintegra.Entidad, Pintegra.Periodo);
            jProgressBar1.setVisible(true);
            int Contador = 20;
            for (int i = 0; i < 24; i++) {
                regTMPSQL = S.Total_Reg_TMP_SqlServer(ArrayTablasSQLSERVER[i]);
                regTMPOracle = Q.Total_Reg_TMP_Oracle(ArrayTablasOracle[i], Pintegra.Entidad, Pintegra.Periodo);
                Texto = Texto + "" + ArrayTablasSQLSERVER[i] + ": \n"
                        + "Reg_SQL:" + regTMPSQL + "  Reg_TMPOracle:" + regTMPOracle + "\n \n";
                jProgressBar1.setValue(Contador);
                Contador = Contador + 4;
            }   jTextArea1.setText(Texto);
            jButton1.setEnabled(true);
            jTextArea1.setVisible(true);
            if (ArrayErroresIns.size() > 0) {
                String[] errorarray;
                String part0 = "", part1 = "", part2 = "", part3 = "";
                DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
                Object[] fila = new Object[5];
                for (int j = 0; j < ArrayErroresIns.size(); j++) {
                    String Datos = Arrays.toString(ArrayErroresIns.get(j)).replace("[", "").replace("]", "");
                    errorarray = Datos.split(",");
                    part0 = errorarray[0].trim();
                    part1 = errorarray[1].trim();
                    part2 = errorarray[2].trim();
                    part3 = errorarray[3].trim();
                    fila[0] = part0;
                    fila[1] = part1;
                    fila[2] = part2;
                    fila[3] = part3;
                    TablaError.addRow(fila);
                    Class<?> col_class = jTable1.getColumnClass(0);
                    jTable1.setDefaultEditor(col_class, null);
                }
                ExportaEi.setVisible(true);
            } else {
                
                JOptionPane.showMessageDialog(null, "No se encontraron registros con Error de insert", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
        } catch (SQLException ex) {
            Logger.getLogger(Errores_insertTMP.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        IntegraTMP.ventanaAbierta=false;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Errores_insertTMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Errores_insertTMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Errores_insertTMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Errores_insertTMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Errores_insertTMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExportaEi;
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
