/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_SENAP;

import ValidacionesSENAP.ExportaxlsxValida;
import ValidacionesSENAP.VCarpetaInvetigacion;
import ValidacionesSENAP.VDeterminacion;
import ValidacionesSENAP.VMASC;
import ValidacionesSENAP.VSentencia;
import java.awt.Color;
import java.io.IOException;
import java.sql.Array;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.org.inegi.Procedure.SENAP.EliminaTMPSENAP;
import mx.org.inegi.QuerysGeneralSQLSERVER.SENAP.QuerySQLServer;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_ACTOSINVESTIGACION;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_ASEGURAMIENTOS;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_ATENCIONES;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_CARPETAINVESTIGACION;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_DELITOS;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_DETERMINACION;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_DIRECCIONUBICACION;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_ETAPAINTERMEDIA;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_ETAPAINVESTIGACION;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_IMPUTADO;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_IMPUTADODELITO;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_INVESTIGACIONCOMPLEMENTARIA;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_MANDAMIENTOSJUDICIALES;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_MASC;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_MEDIDASCAUTELARES;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_MEDIDAS_PROTECCION;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_NOTICIACRIMINAL;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_PROCESO;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_SENTENCIA;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_SOBRESEIMIENTO;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_SUSPENSIONCONDICIONAL;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_VICTIMAIMPUTADO;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_VICTIMAS;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_VICTIMASDELITO;

/**
 *
 * @author ANTONIO.CORIA
 */
public class IntegraTMP extends javax.swing.JFrame {

    /**
     * Creates new form IntegraTMP
     */
    public static String Entidad = "", Periodo = "", BDSQL = "", Server = "", Usuario = "", Pass = "";
    public static boolean ventanaAbierta = false;
    public static  boolean selectServidor = false;
    ArrayList<String[]> ArrayResult;

    public IntegraTMP() {
        initComponents();
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        jLabel5.setVisible(false);
        jProgressBar1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CEntidad = new javax.swing.JComboBox();
        ENVIO1 = new javax.swing.JLabel();
        TPeriodo = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        Ttabla = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TLogin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TPassword = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CBDSQL = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        TServerName = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo CNG.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setText("SENAP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(158, 158, 158)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setText("Entidad:");

        CEntidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));

        ENVIO1.setText("Periodo:");

        jLabel5.setText("Progreso...");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Insertar.png"))); // NOI18N
        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/errorins.png"))); // NOI18N
        jButton2.setToolTipText("Errores de Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nota.png"))); // NOI18N
        jToggleButton2.setText("Nota");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Param Conexion"));

        jLabel7.setText("Login:");

        jLabel8.setText("Password:");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ConexionSqlServer.png"))); // NOI18N
        jButton3.setToolTipText("Conectar a base de datos SQL Server");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("BD Sql Server");

        jLabel9.setText("Server Name:");

        jRadioButton1.setText("Server SQL INEGI");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(CBDSQL, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addComponent(TLogin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TServerName, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TServerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBDSQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ENVIO1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(TPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Ttabla, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ENVIO1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Ttabla, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void muestra() {
        jLabel5.setVisible(true);
        jProgressBar1.setVisible(true);
        jButton1.setEnabled(false);
        TServerName.setEnabled(false);
        TLogin.setEnabled(false);
        TPassword.setEnabled(false);
    }

    public void oculta() {
        jLabel5.setVisible(false);
        Ttabla.setText("");
        jProgressBar1.setVisible(false);
        jButton1.setEnabled(true);
        jButton1.setEnabled(true);
        TServerName.setEnabled(true);
        TLogin.setEnabled(true);
        TPassword.setEnabled(true);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        TMP_SENAP_ATENCIONES AT = new TMP_SENAP_ATENCIONES();
        TMP_SENAP_CARPETAINVESTIGACION CI = new TMP_SENAP_CARPETAINVESTIGACION();
        TMP_SENAP_NOTICIACRIMINAL NC = new TMP_SENAP_NOTICIACRIMINAL();
        TMP_SENAP_DIRECCIONUBICACION DC = new TMP_SENAP_DIRECCIONUBICACION();
        TMP_SENAP_ASEGURAMIENTOS AS = new TMP_SENAP_ASEGURAMIENTOS();
        TMP_SENAP_ACTOSINVESTIGACION AI = new TMP_SENAP_ACTOSINVESTIGACION();
        TMP_SENAP_DELITOS DEL = new TMP_SENAP_DELITOS();
        TMP_SENAP_VICTIMAS VIC = new TMP_SENAP_VICTIMAS();
        TMP_SENAP_VICTIMASDELITO VICDEL = new TMP_SENAP_VICTIMASDELITO();
        TMP_SENAP_MEDIDAS_PROTECCION MEDP = new TMP_SENAP_MEDIDAS_PROTECCION();
        TMP_SENAP_IMPUTADO IMP = new TMP_SENAP_IMPUTADO();
        TMP_SENAP_IMPUTADODELITO IMPD = new TMP_SENAP_IMPUTADODELITO();
        TMP_SENAP_VICTIMAIMPUTADO VICIMP = new TMP_SENAP_VICTIMAIMPUTADO();
        TMP_SENAP_DETERMINACION DET = new TMP_SENAP_DETERMINACION();
        TMP_SENAP_PROCESO PROC = new TMP_SENAP_PROCESO();
        TMP_SENAP_MASC MASC = new TMP_SENAP_MASC();
        TMP_SENAP_ETAPAINVESTIGACION ETP = new TMP_SENAP_ETAPAINVESTIGACION();
        TMP_SENAP_MANDAMIENTOSJUDICIALES MJ = new TMP_SENAP_MANDAMIENTOSJUDICIALES();
        TMP_SENAP_INVESTIGACIONCOMPLEMENTARIA IC = new TMP_SENAP_INVESTIGACIONCOMPLEMENTARIA();
        TMP_SENAP_MEDIDASCAUTELARES MC = new TMP_SENAP_MEDIDASCAUTELARES();
        TMP_SENAP_ETAPAINTERMEDIA EIN = new TMP_SENAP_ETAPAINTERMEDIA();
        TMP_SENAP_SOBRESEIMIENTO SOB = new TMP_SENAP_SOBRESEIMIENTO();
        TMP_SENAP_SUSPENSIONCONDICIONAL SUSC = new TMP_SENAP_SUSPENSIONCONDICIONAL();
        TMP_SENAP_SENTENCIA SENT = new TMP_SENAP_SENTENCIA();

        new Thread(() -> {
            try {

                int respuesta = JOptionPane.showConfirmDialog(null, "¿Estas seguro de insertar a TMP?", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (respuesta == JOptionPane.YES_OPTION) {
                    if (!TPeriodo.getText().equals("")) {
                        if (CBDSQL.getSelectedItem() != null) {
                            Valores();
                            muestra();
                            EliminaTMPSENAP Elim = new EliminaTMPSENAP();
                            Elim.EliminaTMPSENAP(Entidad, Periodo);
                            jProgressBar1.setValue(5);
                            Ttabla.setText("Ins..TMP_SENAP_DIRECCIONUBICACION");
                            DC.TMP_SENAP_DIRECCIONUBICACION(Entidad, Periodo);
                            jProgressBar1.setValue(10);
                            Ttabla.setText("Ins..TMP_SENAP_NOTICIACRIMINAL");
                            NC.TMP_SENAP_NOTICIACRIMINAL(Entidad, Periodo);
                            jProgressBar1.setValue(15);
                            Ttabla.setText("Ins..TMP_SENAP_ATENCIONES");
                            AT.TMP_SENAP_ATENCIONES(Entidad, Periodo);
                            jProgressBar1.setValue(20);
                            Ttabla.setText("Ins..TMP_SENAP_CARPETAINVESTIGACION");
                            CI.TMP_SENAP_CARPETAINVESTIGACION(Entidad, Periodo);
                            jProgressBar1.setValue(25);
                            Ttabla.setText("Ins..TMP_SENAP_ASEGURAMIENTOS");
                            AS.TMP_SENAP_ASEGURAMIENTOS(Entidad, Periodo);
                            jProgressBar1.setValue(30);
                            Ttabla.setText("Ins..TMP_SENAP_ACTOSINVESTIGACION");
                            AI.TMP_SENAP_ACTOSINVESTIGACION(Entidad, Periodo);
                            jProgressBar1.setValue(35);
                            Ttabla.setText("Ins..TMP_SENAP_DELITOS");
                            DEL.TMP_SENAP_DELITOS(Entidad, Periodo);
                            jProgressBar1.setValue(40);
                            Ttabla.setText("Ins..TMP_SENAP_VICTIMAS");
                            VIC.TMP_SENAP_VICTIMAS(Entidad, Periodo);
                            jProgressBar1.setValue(45);
                            Ttabla.setText("Ins..TMP_SENAP_VICTIMASDELITO");
                            VICDEL.TMP_SENAP_VICTIMASDELITO(Entidad, Periodo);
                            jProgressBar1.setValue(50);
                            Ttabla.setText("Ins..TMP_SENAP_MEDIDAS_PROTECCION");
                            MEDP.TMP_SENAP_MEDIDAS_PROTECCION(Entidad, Periodo);
                            jProgressBar1.setValue(55);
                            Ttabla.setText("Ins..TMP_SENAP_IMPUTADO");
                            IMP.TMP_SENAP_IMPUTADO(Entidad, Periodo);
                            jProgressBar1.setValue(60);
                            Ttabla.setText("Ins..TMP_SENAP_IMPUTADODELITO");
                            IMPD.TMP_SENAP_IMPUTADODELITO(Entidad, Periodo);
                            jProgressBar1.setValue(65);
                            Ttabla.setText("Ins..TMP_SENAP_VICTIMAIMPUTADO");
                            VICIMP.TMP_SENAP_VICTIMAIMPUTADO(Entidad, Periodo);
                            jProgressBar1.setValue(70);
                            Ttabla.setText("Ins..TMP_SENAP_DETERMINACION");
                            DET.TMP_SENAP_DETERMINACION(Entidad, Periodo);
                            jProgressBar1.setValue(75);
                            Ttabla.setText("Ins..TMP_SENAP_PROCESO");
                            PROC.TMP_SENAP_PROCESO(Entidad, Periodo);
                            jProgressBar1.setValue(80);
                            Ttabla.setText("Ins..TMP_SENAP_MASC");
                            MASC.TMP_SENAP_MASC(Entidad, Periodo);
                            jProgressBar1.setValue(85);
                            Ttabla.setText("Ins..TMP_SENAP_ETAPAINVESTIGACION");
                            ETP.TMP_SENAP_ETAPAINVESTIGACION(Entidad, Periodo);
                            jProgressBar1.setValue(87);
                            Ttabla.setText("Ins..TMP_SENAP_MANDAMIENTOSJUDICIALES");
                            MJ.TMP_SENAP_MANDAMIENTOSJUDICIALES(Entidad, Periodo);
                            jProgressBar1.setValue(88);
                            Ttabla.setText("Ins..TMP_SENAP_INVESTIGACIONCOMPLEMENTARIA");
                            IC.TMP_SENAP_INVESTIGACIONCOMPLEMENTARIA(Entidad, Periodo);
                            jProgressBar1.setValue(90);
                            Ttabla.setText("Ins..TMP_SENAP_MEDIDASCAUTELARES");
                            MC.TMP_SENAP_MEDIDASCAUTELARES(Entidad, Periodo);
                            jProgressBar1.setValue(92);
                            Ttabla.setText("Ins..TMP_SENAP_ETAPAINTERMEDIA");
                            EIN.TMP_SENAP_ETAPAINTERMEDIA(Entidad, Periodo);
                            jProgressBar1.setValue(94);
                            Ttabla.setText("Ins..TMP_SENAP_SOBRESEIMIENTO");
                            SOB.TMP_SENAP_SOBRESEIMIENTO(Entidad, Periodo);
                            jProgressBar1.setValue(96);
                            Ttabla.setText("Ins..TMP_SENAP_SUSPENSIONCONDICIONAL");
                            SUSC.TMP_SENAP_SUSPENSIONCONDICIONAL(Entidad, Periodo);
                            jProgressBar1.setValue(98);
                            Ttabla.setText("Ins..TMP_SENAP_SENTENCIA");
                            SENT.TMP_SENAP_SENTENCIA(Entidad, Periodo);
                            jProgressBar1.setValue(100);
                            oculta();
                            JOptionPane.showMessageDialog(null, "Se han insertado los registros Correctamente, favor de revisar ventana Errores de Insert");
                        } else {
                            JOptionPane.showMessageDialog(null, "Favor de Seleccionar BD a Importar");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Favor de capturar Periodo");
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(IntegraTMP.class.getName()).log(Level.SEVERE, null, ex);
            }

        }).start();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Valores();
        if (!TPeriodo.getText().equals("") && !CEntidad.getSelectedItem().toString().equals("") && CBDSQL.getItemCount() > 0) {
            if (!ventanaAbierta) {
                ventanaAbierta = true;
                Errores_insertTMP Errores = new Errores_insertTMP();
                Errores.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Ventana Errores de insert abierta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Favor de capturar Periodo y seleccionar una bd sql server");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Inicio in = new Inicio();
        in.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        Nota nota = new Nota();
        nota.setVisible(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Valores();
            if (!TServerName.getText().equals("") && !TLogin.getText().equals("") && !TPassword.getText().equals("")) {
                QuerySQLServer SQL = new QuerySQLServer();
                ArrayResult = SQL.Nombre_Base();
                CBDSQL.removeAllItems();
                for (String[] elemento : ArrayResult) {
                    CBDSQL.addItem(elemento[0]);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Favor de capturar parametros de conexion!");
                // JOptionPane.showMessageDialog(null, "Hola Anita esto lo acabo de actualizar!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(IntegraTMP.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error de Conexion" + ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
       // JOptionPane.showMessageDialog(null, "Por el momento no se encuentra habilitado el espacio en el servidor INEGI");
       // jRadioButton1.setSelected(false);  
       if (jRadioButton1.isSelected()==true){
        selectServidor=true;   
        TServerName.setText("W-BDCLPRO8\\BD8");
        TLogin.setText("senap.owner");
        TPassword.setText("Inegi_Senap2025");    
        //JOptionPane.showMessageDialog(null, "Por el momento no se encuentra habilitado el espacio en el servidor INEGI");
       }else{
        selectServidor=false;   
        TServerName.setText("");
        TLogin.setText("");
        TPassword.setText("");
       }
        
        
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    public void Valores() {
        Entidad = CEntidad.getSelectedItem().toString();
        Periodo = TPeriodo.getText().trim();
        if (CBDSQL.getSelectedItem() != null) {
            BDSQL = CBDSQL.getSelectedItem().toString();
        }
        Server = TServerName.getText();
        Usuario = TLogin.getText();
        Pass = TPassword.getText();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntegraTMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntegraTMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntegraTMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntegraTMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntegraTMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBDSQL;
    private javax.swing.JComboBox CEntidad;
    private javax.swing.JLabel ENVIO1;
    private javax.swing.JTextField TLogin;
    private javax.swing.JPasswordField TPassword;
    private javax.swing.JTextField TPeriodo;
    private javax.swing.JTextField TServerName;
    private javax.swing.JLabel Ttabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
