/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_SENAP;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.org.inegi.Procedure.SENAP.Agrega_CarpetaID;
import mx.org.inegi.Procedure.SENAP.EliminaTRSENAP;
import mx.org.inegi.QuerysGeneralOracle.SENAP.QueryOracle;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_ACTOSINVESTIGACION;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_ASEGURAMIENTOS;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_ATENCIONES;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_CARPETAINVESTIGACION;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_DELITOS;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_DETERMINACION;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_DIRECCIONUBICACION;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_ETAPAINTERMEDIA;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_ETAPAINVESTIGACION;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_IMPUTADO;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_IMPUTADODELITO;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_INVESTIGACIONCOMPLEMENTARIA;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_MANDAMIENTOSJUDICIALES;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_MASC;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_MEDIDASCAUTELARES;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_MEDIDAS_PROTECCION;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_NOTICIACRIMINAL;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_PROCESO;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_SENTENCIA;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_SOBRESEIMIENTO;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_SUSPENSIONCONDICIONAL;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_VICTIMAIMPUTADO;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_VICTIMAS;
import mx.org.inegi.insert_TR_SENAP.TR_SENAP_VICTIMASDELITO;

/**
 *
 * @author ANTONIO.CORIA
 */
public class IntegraTR extends javax.swing.JFrame {

    public static String Entidad = "", Periodo = "", Estatus = "";
    public static boolean ventanaAbierta = false;

    /**
     * Creates new form IntegraTR
     */
    public IntegraTR() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        LTabla.setVisible(false);
        Progress.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CEntidad = new javax.swing.JComboBox();
        ENVIO1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CEstatus = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        CPeriodo = new javax.swing.JComboBox();
        Progress = new javax.swing.JProgressBar();
        LTabla = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo CNG.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setText("SENAP");

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jLabel4.setText("Entidad:");

        CEntidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));
        CEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEntidadActionPerformed(evt);
            }
        });

        ENVIO1.setText("Periodo:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refresh.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Estatus:");

        CEstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "En Revision de Integracion TR", "Liberado", "En Validacion" }));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InsertaBD.png"))); // NOI18N
        jButton3.setText("Insertar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/errorins.png"))); // NOI18N
        jButton2.setToolTipText("Errores de Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        CPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPeriodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ENVIO1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CPeriodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(131, 131, 131)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(91, 91, 91))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(LTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ENVIO1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(LTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Progress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (CPeriodo.getItemCount() == 0) {
            JOptionPane.showMessageDialog(null, "Favor de Seleccionar Periodo");
        } else {
            QueryOracle Q = new QueryOracle();
            Valores();
            try {
                Q.Actualiza_Estatus_RES_tr_senap_Control(Entidad, Periodo, CEstatus.getSelectedItem().toString());
            } catch (SQLException ex) {
                Logger.getLogger(IntegraTR.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Cambio de estatus correctamente");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void LLena_combo_Periodo() {
        QueryOracle Q = new QueryOracle();
        String valor;
        ArrayList<String[]> Array;
        try {
            CPeriodo.removeAllItems();
            Array = Q.Periodo(CEntidad.getSelectedItem().toString());
            for (String[] elemento : Array) {
                CPeriodo.addItem(elemento[0]);
            }
            if (CPeriodo.getItemCount()>0)
            {
             Valores();   
             valor=Q.Estatus_Control(Entidad, Periodo);
            CEstatus.setSelectedItem(valor);
               if(CEstatus.getSelectedItem().toString().equals("Liberado")){
                  CEstatus.setEnabled(false);
                  jButton1.setEnabled(false);
                   
               }else{
                  CEstatus.setEnabled(true);
                  jButton1.setEnabled(true); 
               }
            }
        } catch (SQLException ex) {
            Logger.getLogger(IntegraTR.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        QueryOracle Q = new QueryOracle();
        TR_SENAP_DIRECCIONUBICACION TA1 = new TR_SENAP_DIRECCIONUBICACION();
        TR_SENAP_NOTICIACRIMINAL TA2 = new TR_SENAP_NOTICIACRIMINAL();
        TR_SENAP_CARPETAINVESTIGACION TA3 = new TR_SENAP_CARPETAINVESTIGACION();
        TR_SENAP_ATENCIONES TA4 = new TR_SENAP_ATENCIONES();
        TR_SENAP_ASEGURAMIENTOS TA5 = new TR_SENAP_ASEGURAMIENTOS();
        TR_SENAP_ACTOSINVESTIGACION TA6 = new TR_SENAP_ACTOSINVESTIGACION();
        TR_SENAP_DELITOS TA7 = new TR_SENAP_DELITOS();
        TR_SENAP_VICTIMAS TA8 = new TR_SENAP_VICTIMAS();
        TR_SENAP_VICTIMASDELITO TA9 = new TR_SENAP_VICTIMASDELITO();
        TR_SENAP_MEDIDAS_PROTECCION TA10 = new TR_SENAP_MEDIDAS_PROTECCION();
        TR_SENAP_IMPUTADO TA11 = new TR_SENAP_IMPUTADO();
        TR_SENAP_IMPUTADODELITO TA12 = new TR_SENAP_IMPUTADODELITO();
        TR_SENAP_VICTIMAIMPUTADO TA13 = new TR_SENAP_VICTIMAIMPUTADO();
        TR_SENAP_DETERMINACION TA14 = new TR_SENAP_DETERMINACION();
        TR_SENAP_PROCESO TA15 = new TR_SENAP_PROCESO();
        TR_SENAP_MASC TA16 = new TR_SENAP_MASC();
        TR_SENAP_ETAPAINVESTIGACION TA17 = new TR_SENAP_ETAPAINVESTIGACION();
        TR_SENAP_MANDAMIENTOSJUDICIALES TA18 = new TR_SENAP_MANDAMIENTOSJUDICIALES();
        TR_SENAP_INVESTIGACIONCOMPLEMENTARIA TA19 = new TR_SENAP_INVESTIGACIONCOMPLEMENTARIA();
        TR_SENAP_MEDIDASCAUTELARES TA20 = new TR_SENAP_MEDIDASCAUTELARES();
        TR_SENAP_ETAPAINTERMEDIA TA21 = new TR_SENAP_ETAPAINTERMEDIA();
        TR_SENAP_SOBRESEIMIENTO TA22 = new TR_SENAP_SOBRESEIMIENTO();
        TR_SENAP_SUSPENSIONCONDICIONAL TA23 = new TR_SENAP_SUSPENSIONCONDICIONAL();
        TR_SENAP_SENTENCIA TA24 = new TR_SENAP_SENTENCIA();
        new Thread(() -> {
            try {
                if (CPeriodo.getItemCount() == 0) {
                    JOptionPane.showMessageDialog(null, "Favor de seleccionar Periodo");
                } else {
                    Valores();
                    Estatus = Q.Estatus_Control(Entidad, Periodo);
                    if (!Estatus.equals("Liberado")) {
                        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estas seguro de insertar a TR?", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (respuesta == JOptionPane.YES_OPTION) {
                            jButton3.setEnabled(false);
                            LTabla.setVisible(true);
                            Progress.setVisible(true);
                            CEntidad.setEnabled(false);
                            CPeriodo.setEnabled(false);
                            CEstatus.setEnabled(false);
                            jButton1.setEnabled(false);
                            jButton2.setEnabled(false);
                           EliminaTRSENAP ELTR = new EliminaTRSENAP();
                            ELTR.EliminaTRSENAP(Entidad, Periodo);
                            Q.Limpia_RES_tr_senap_Control(Entidad, Periodo);
                            Q.Inserta_RES_tr_senap_Control(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_DIRECCIONUBICACION");
                            Progress.setValue(5);
                            TA1.TR_SENAP_DIRECCIONUBICACION(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_NOTICIACRIMINAL");
                            Progress.setValue(7);
                            TA2.TR_SENAP_NOTICIACRIMINAL(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_CARPETAINVESTIGACION");
                            Progress.setValue(10);
                            TA3.TR_SENAP_CARPETAINVESTIGACION(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_ATENCIONES");
                            Progress.setValue(15);
                            TA4.TR_SENAP_ATENCIONES(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_ASEGURAMIENTOS");
                            Progress.setValue(20);
                            TA5.TR_SENAP_ASEGURAMIENTOS(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_ACTOSINVESTIGACION");
                            Progress.setValue(25);
                            TA6.TR_SENAP_ACTOSINVESTIGACION(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_DELITOS");
                            Progress.setValue(30);
                            TA7.TR_SENAP_DELITOS(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_VICTIMAS");
                            Progress.setValue(35);
                            TA8.TR_SENAP_VICTIMAS(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_VICTIMASDELITO");
                            Progress.setValue(40);
                            TA9.TR_SENAP_VICTIMASDELITO(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_MEDIDAS_PROTECCION");
                            Progress.setValue(45);
                            TA10.TR_SENAP_MEDIDAS_PROTECCION(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_IMPUTADO");
                            Progress.setValue(50);
                            TA11.TR_SENAP_IMPUTADO(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_IMPUTADODELITO");
                            Progress.setValue(55);
                            TA12.TR_SENAP_IMPUTADODELITO(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_VICTIMAIMPUTADO");
                            Progress.setValue(60);
                            TA13.TR_SENAP_VICTIMAIMPUTADO(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_DETERMINACION");
                            Progress.setValue(65);
                            TA14.TR_SENAP_DETERMINACION(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_PROCESO");
                            Progress.setValue(70);
                            TA15.TR_SENAP_PROCESO(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_MASC");
                            Progress.setValue(75);
                            TA16.TR_SENAP_MASC(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_ETAPAINVESTIGACION");
                            Progress.setValue(80);
                            TA17.TR_SENAP_ETAPAINVESTIGACION(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_MANDAMIENTOSJUDICIALES");
                            Progress.setValue(85);
                            TA18.TR_SENAP_MANDAMIENTOSJUDICIALES(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_INVESTIGACIONCOMPLEMENTARIA");
                            Progress.setValue(90);
                            TA19.TR_SENAP_INVESTIGACIONCOMPLEMENTARIA(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_MEDIDASCAUTELARES");
                            Progress.setValue(95);
                            TA20.TR_SENAP_MEDIDASCAUTELARES(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_ETAPAINTERMEDIA");
                            Progress.setValue(97);
                            TA21.TR_SENAP_ETAPAINTERMEDIA(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_SOBRESEIMIENTO");
                            Progress.setValue(98);
                            TA22.TR_SENAP_SOBRESEIMIENTO(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_SUSPENSIONCONDICIONAL");
                            Progress.setValue(99);
                            TA23.TR_SENAP_SUSPENSIONCONDICIONAL(Entidad, Periodo);
                            LTabla.setText("...Insertando RES_TR_SENAP_SENTENCIA");
                            Progress.setValue(100);
                            TA24.TR_SENAP_SENTENCIA(Entidad, Periodo);
                            Agrega_CarpetaID car=new Agrega_CarpetaID();
                            car.Agrega_CarpetaID(Entidad, Periodo);
                            JOptionPane.showMessageDialog(null, "La informacion se ha insertado favor de revisar Ventana Errores de insert");
                            CEntidad.setEnabled(true);
                            CPeriodo.setEnabled(true);
                            jButton3.setEnabled(true);
                            LTabla.setVisible(false);
                            Progress.setVisible(false);
                            CEstatus.setEnabled(true);
                            jButton1.setEnabled(true);
                            jButton2.setEnabled(true);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Informacion con Entidad="+Entidad+" y periodo="+Periodo+" se encuentra en estatus Liberada.Favor de contactar al administrador");
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(IntegraTR.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(IntegraTR.class.getName()).log(Level.SEVERE, null, ex);
            }

        }).start();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if (CPeriodo.getItemCount() == 0) {
            JOptionPane.showMessageDialog(null, "Favor de Seleccionar Periodo");
        } else {
            if (!ventanaAbierta) {
                ventanaAbierta = true;
                Valores();
                Errores_insertTR Errores = new Errores_insertTR();
                Errores.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Ventana Errores de insert abierta");
            }

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Inicio In = new Inicio();
        In.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void CEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEntidadActionPerformed
        // TODO add your handling code here:
        LLena_combo_Periodo();
    }//GEN-LAST:event_CEntidadActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        LLena_combo_Periodo();
    }//GEN-LAST:event_formWindowOpened

    private void CPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPeriodoActionPerformed
        // TODO add your handling code here:
        if (CPeriodo.getItemCount()>0)
        {
            QueryOracle Q = new QueryOracle();
            String valor = "";
            Valores();   
            
            try {
                valor=Q.Estatus_Control(Entidad, Periodo);
                CEstatus.setSelectedItem(valor);
                if(CEstatus.getSelectedItem().toString().equals("Liberado")){
                  CEstatus.setEnabled(false);
                  jButton1.setEnabled(false);  
               }else{
                  CEstatus.setEnabled(true);
                  jButton1.setEnabled(true); 
               }
            } catch (SQLException ex) {
                Logger.getLogger(IntegraTR.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
        
    }//GEN-LAST:event_CPeriodoActionPerformed

    public void Valores() {
        Entidad = CEntidad.getSelectedItem().toString();
        Periodo = CPeriodo.getSelectedItem().toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntegraTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntegraTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntegraTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntegraTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntegraTR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CEntidad;
    private javax.swing.JComboBox CEstatus;
    private javax.swing.JComboBox CPeriodo;
    private javax.swing.JLabel ENVIO1;
    private javax.swing.JLabel LTabla;
    private javax.swing.JProgressBar Progress;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
