/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_Menu;

import Pantallas_PLE.Menu;
import Pantallas_SENAP.Inicio;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.org.inegi.conexion.SENAP.ConSQLServer;
import mx.org.inegi.conexion.SENAP.ConORACLEFactory;
import mx.org.inegi.insert_TMP_SENAP.TMP_SENAP_NOTICIACRIMINAL;

/**
 *
 * @author ANTONIO.CORIA
 */
public class MenuProyectos extends javax.swing.JFrame {

    /**
     * Creates new form MenuProyectos
     */
    public MenuProyectos() {
        initComponents();
        this.setLocationRelativeTo(null);
        PLE.setVisible(false);
        PS.setVisible(false);
        PS2.setVisible(false);
        jToggleButton1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        PS = new javax.swing.JButton();
        PS2 = new javax.swing.JButton();
        PLE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PS3 = new javax.swing.JButton();
        PS4 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Senap.png"))); // NOI18N
        jButton1.setText("SENAP");
        jButton1.setToolTipText("Sistema Estadistico Nacional de Procuracion de Justicia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 230, 120));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JALogo.png"))); // NOI18N
        jToggleButton1.setText("JA");
        jToggleButton1.setToolTipText("Justicia Agraria");
        jPanel3.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 190, 120));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Modulos DMED");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 200, -1));

        PS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PSF.png"))); // NOI18N
        PS.setText("PSF Y CPF");
        PS.setToolTipText("Programas Sociales Federal y Contrataciones Publicas Federal");
        PS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSActionPerformed(evt);
            }
        });
        jPanel3.add(PS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 230, 130));

        PS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TEPJF.png"))); // NOI18N
        PS2.setText("TEPJF");
        PS2.setToolTipText("Tribunal Electoral Poder Judicial de la Federacion");
        PS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PS2ActionPerformed(evt);
            }
        });
        jPanel3.add(PS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 190, 126));

        PLE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PLE.png"))); // NOI18N
        PLE.setText("PLE");
        PLE.setToolTipText("Poderes Legislativos Estatal");
        PLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLEActionPerformed(evt);
            }
        });
        jPanel3.add(PLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu2.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 850, 520));

        PS3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CPF.png"))); // NOI18N
        PS3.setText("CPF");
        PS3.setToolTipText("Contrataciones Publicas Federal");
        PS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PS3ActionPerformed(evt);
            }
        });
        jPanel3.add(PS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 190, 126));

        PS4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CPF.png"))); // NOI18N
        PS4.setText("CPF");
        PS4.setToolTipText("Contrataciones Publicas Federal");
        PS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PS4ActionPerformed(evt);
            }
        });
        jPanel3.add(PS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 190, 126));

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JALogo.png"))); // NOI18N
        jToggleButton2.setText("JA");
        jToggleButton2.setToolTipText("Justicia Agraria");
        jPanel3.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 190, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLEActionPerformed
        // TODO add your handling code here:
        Menu Men=new Menu();
        Men.setVisible(true);
        this.setVisible(false);
        System.out.println("Prueba de cambio");

        
    }//GEN-LAST:event_PLEActionPerformed

    private void PSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSActionPerformed
        // TODO add your handling code here:
        Pantallas_PSF.MenuPSF men=new Pantallas_PSF.MenuPSF();
        men.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_PSActionPerformed

    private void PS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PS2ActionPerformed
        // TODO add your handling code here:
        Pantallas_TEPJF.Menu TE=new Pantallas_TEPJF.Menu();
        TE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PS2ActionPerformed

    private void PS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PS3ActionPerformed

    private void PS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PS4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PS4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Inicio In=new Inicio();
        In.setVisible(true);
        this.setVisible(false);
 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProyectos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PLE;
    private javax.swing.JButton PS;
    private javax.swing.JButton PS2;
    private javax.swing.JButton PS3;
    private javax.swing.JButton PS4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
